#!/usr/bin/env bash
# Review build (claim C2_dense_prefill/f16x_db_bn64): baseline from the UNMODIFIED in-tree source with
# the production flags, the engineer's ../../cand.hip with the same flags, and the review harness
# (engineer's harness.cpp + extended correctness tails, generated by mk_harness.py).
set -eu
cd "$(dirname "$0")"
source ../../../_infra/env.sh
echo "KFLAGS_V41=$KFLAGS_V41"
../../../_infra/kcc.sh $KFLAGS_V41 --genco --offload-arch=gfx1201 "$KERNELS_DIR/q8_0_matvec_wmma.hip" -o base_q8_0_matvec_wmma_gfx1201.hsaco
../../../_infra/kcc.sh $KFLAGS_V41 --genco --offload-arch=gfx1201 ../../cand.hip -o cand_gfx1201.hsaco
../../../_infra/kcc.sh -O2 --offload-arch=gfx1201 harness_review.cpp -o harness_review_gfx1201
echo built
