//! GENERATED by scripts/v41_oracle/gen_prompt_vectors.py-adjacent extraction from
//! DeepSeek-V4.1 `encoding/encoding.py` — the tool-schema preamble split around
//! the schemas list, byte-exact. Do not edit by hand.

pub const TOOLS_HEAD: &str = r#"## Tools

You have access to a set of tools to help answer the user's question. You can invoke tools by writing a "<｜DSML｜ calls>" block like the following:

<｜DSML｜ calls>
<｜DSML｜ invoke name="$TOOL_NAME">
<｜DSML｜ parameter name="$PARAMETER_NAME" string="true|false">$PARAMETER_VALUE</｜DSML｜ parameter>
...
</｜DSML｜ invoke>
<｜DSML｜ invoke name="$TOOL_NAME2">
...
</｜DSML｜ invoke>
</｜DSML｜ calls>

String parameters should be specified as is and set `string="true"`. For all other types (numbers, booleans, arrays, objects), pass the value in JSON format and set `string="false"`.

If thinking_mode is enabled (triggered by <think>), you MUST output your complete reasoning inside <think>...</think> BEFORE any tool calls or final response.

Otherwise, output directly after </think> with tool calls or final response.

### Available Tool Schemas

"#;
pub const TOOLS_TAIL: &str = r#"

You MUST strictly follow the above defined tool name and parameter schemas to invoke tool calls.
"#;
pub const REASONING_EFFORT_FMT_PREFIX: &str = r#"Reasoning Effort: "#;
pub const REASONING_EFFORT_FMT_SUFFIX: &str = r#" (range 1-100, the higher the value, the more thorough the reasoning)

"#;
pub const RESPONSE_FORMAT_PREFIX: &str = r#"## Response Format:

You MUST strictly adhere to the following schema to reply:
"#;
