//! V4.1 chat encoding vs DeepSeek's reference encoder: every case in
//! `tests/fixtures/v41_prompts.json` (generated by
//! `scripts/v41_oracle/gen_prompt_vectors.py` from `encoding/encoding.py`)
//! must render byte-identically.
use deepstrix_server::openai::types::{ChatMessage, ToolDef};
use deepstrix_server::prompt_v41::{render_prompt_text_v41, V41Effort};

#[test]
fn v41_prompts_match_reference() {
    let raw = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/v41_prompts.json")).unwrap();
    let cases: Vec<serde_json::Value> = serde_json::from_str(&raw).unwrap();
    let (mut ok, mut skipped, mut failed) = (0, Vec::new(), Vec::new());
    for c in &cases {
        let name = c["name"].as_str().unwrap();
        let Some(expected) = c["expected"].as_str() else { skipped.push(format!("{name} (reference errored)")); continue };
        let msgs_json = c["messages"].as_array().unwrap();
        // Unsupported inputs: latest_reminder role, message-level response_format.
        if msgs_json.iter().any(|m| m["role"] == "latest_reminder" || m.get("response_format").is_some()) {
            skipped.push(format!("{name} (unsupported field)"));
            continue;
        }
        let tools: Option<Vec<ToolDef>> = msgs_json[0].get("tools").map(|t| serde_json::from_value(t.clone()).unwrap());
        let messages: Vec<ChatMessage> = msgs_json
            .iter()
            .enumerate()
            .map(|(i, m)| {
                let mut m = m.clone();
                m.as_object_mut().unwrap().remove("tools");
                // The reference tolerates tool calls without ids (sorted as unknown);
                // the server's wire type requires one — inject placeholders that no
                // tool result references, which keeps the reference's stable order.
                if let Some(tcs) = m.get_mut("tool_calls").and_then(|t| t.as_array_mut()) {
                    for (j, tc) in tcs.iter_mut().enumerate() {
                        if tc.get("id").is_none() {
                            tc["id"] = serde_json::Value::String(format!("_missing_{i}_{j}"));
                        }
                    }
                }
                serde_json::from_value(m).unwrap_or_else(|e| panic!("{name}: message {i}: {e}"))
            })
            .collect();
        let context: Option<Vec<ChatMessage>> = c["context"].as_array().map(|a| a.iter().map(|m| serde_json::from_value(m.clone()).unwrap()).collect());
        let thinking = c["thinking_mode"].as_str() == Some("thinking");
        let effort = match &c["reasoning_effort"] {
            serde_json::Value::Null => V41Effort::DEFAULT,
            v => V41Effort::from_json(v).unwrap(),
        };
        match render_prompt_text_v41(&messages, tools.as_deref(), thinking, effort, context.as_deref()) {
            Ok(got) if got == expected => ok += 1,
            Ok(got) => {
                let at = got.bytes().zip(expected.bytes()).position(|(a, b)| a != b).unwrap_or(got.len().min(expected.len()));
                failed.push(format!(
                    "{name}: first difference at byte {at}\n   got: {:?}\n  want: {:?}",
                    &got[at.saturating_sub(40)..(at + 60).min(got.len())],
                    &expected[at.saturating_sub(40)..(at + 60).min(expected.len())]
                ));
            }
            Err(e) if e.to_string().contains("image parts") => skipped.push(format!("{name} (images)")),
            Err(e) => failed.push(format!("{name}: error {e}")),
        }
    }
    eprintln!("ok {ok}, skipped {}: {:?}", skipped.len(), skipped);
    for f in &failed {
        eprintln!("FAIL {f}");
    }
    assert!(failed.is_empty(), "{} cases differ from the reference", failed.len());
}
