#!/usr/bin/env python3
"""Generate `crates/v4flash-core/src/tokenizer/joyai_ucd.rs`: the Unicode
class table behind the joyai-llm / deepseek-v3 pre-tokenizer.

The reference pre-tokenizer is Hugging Face `tokenizers`, whose `Split`
regexes run on Oniguruma. Instead of transcribing `unicodedata` (whose Unicode
version differs from Oniguruma's, and whose `\\s` is not Oniguruma's), this
asks THAT engine which codepoints match `\\p{L}`, `\\p{M}`, `\\p{N}`,
`[\\p{P}\\p{S}]` and `\\s`, so the table is the reference's own definition.
`\\p{P}` and `\\p{S}` are merged: the regex only ever uses them together.

Usage (needs the `tokenizers` wheel, e.g. in a throwaway venv):

    python3 -m venv /tmp/tv && /tmp/tv/bin/pip install tokenizers
    /tmp/tv/bin/python scripts/gen_joyai_ucd.py > crates/v4flash-core/src/tokenizer/joyai_ucd.rs
"""

import sys

import tokenizers
from tokenizers import Regex
from tokenizers import pre_tokenizers as pt

CLASSES = [("L", r"\p{L}"), ("M", r"\p{M}"), ("N", r"\p{N}"), ("PS", r"[\p{P}\p{S}]"), ("WS", r"\s")]


def members(text, cps, pat):
    # "removed" keeps exactly the NON-matching stretches (with char offsets);
    # every codepoint outside them matched the single-codepoint class.
    nonmatch = bytearray(len(text))
    for piece, (a, b) in pt.Split(Regex(pat), behavior="removed").pre_tokenize_str(text):
        assert text[a:b] == piece
        nonmatch[a:b] = b"\x01" * (b - a)
    return {cps[i] for i in range(len(text)) if not nonmatch[i]}


def main():
    cps = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    text = "".join(map(chr, cps))
    cls = {}
    for name, pat in CLASSES:
        for cp in members(text, cps, pat):
            assert cp not in cls, f"U+{cp:04X} in both {cls[cp]} and {name}"
            cls[cp] = name
    runs = []
    for cp in sorted(cls):
        if runs and runs[-1][1] == cp - 1 and runs[-1][2] == cls[cp]:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, cls[cp]])

    w = sys.stdout.write
    w("// @generated by scripts/gen_joyai_ucd.py -- do not edit by hand.\n")
    w(f"// Source: Oniguruma as bundled in HF tokenizers {tokenizers.__version__}\n")
    w("// (the engine behind the reference pre_tokenizer); 0.23.2 has Unicode 16.0 tables.\n")
    w("//! Unicode classes for the joyai-llm pre-tokenizer: sorted, disjoint, inclusive\n")
    w("//! codepoint ranges. Codepoints in no range are none of the classes (C*, unassigned).\n\n")
    w("pub(super) const L: u8 = 1; // \\p{L}\n")
    w("pub(super) const M: u8 = 2; // \\p{M}\n")
    w("pub(super) const N: u8 = 3; // \\p{N}\n")
    w("pub(super) const PS: u8 = 4; // \\p{P} | \\p{S}\n")
    w("pub(super) const WS: u8 = 5; // \\s (Oniguruma: the 25 White_Space codepoints)\n\n")
    w("#[rustfmt::skip]\n")
    w(f"pub(super) static RANGES: [(u32, u32, u8); {len(runs)}] = [\n")
    for i in range(0, len(runs), 4):
        w("    " + " ".join(f"(0x{a:05x}, 0x{b:05x}, {k})," for a, b, k in runs[i:i + 4]) + "\n")
    w("];\n")


if __name__ == "__main__":
    main()
