#!/usr/bin/env python3
"""Golden vectors for `v4flash_core::tokenizer`'s joyai-llm pre-tokenizer and
`encode`, produced by the reference: HF `tokenizers` running the model's own
`tokenizer.json` (DeepSeek V4; its pre_tokenizer is the deepseek-v3 one).

Writes crates/v4flash-core/tests/data/joyai_pretok_goldens.json:
  cases  -- text, the reference pre-token pieces, the reference ids
  tokens/merges -- a TRIMMED vocab (real ids, merge order kept) that is
            sufficient by construction for these texts: a merge `A B` can only
            fire if `AB` occurs in the byte-encoded text, and a token can only
            be emitted if its bytes occur there (same criterion as
            gen_tool_prompt_vectors.py).

Usage (needs the `tokenizers` wheel; the tokenizer.json from the model dir, or
from the `deepseek-tokenizer` PyPI wheel, which ships the same file):

    /tmp/tv/bin/python scripts/gen_joyai_pretok_vectors.py <path/to/tokenizer.json>
"""

import json
import os
import sys

from tokenizers import Tokenizer

CASES = [
    # CJK + full-width punctuation (the vocab merges punctuation with "\n").
    "你好。\n",
    "，世界",
    "【注意】请勿删除！\n\n下一段：继续。",
    "deepstrix是一个推理引擎（engine），支持V4。",
    "  中文 和 English 混排",
    # Typographic quotes / dashes / ellipsis.
    "Hello.”\n",
    "He said “hi”, then left… — ‘ok’?\n\nNext",
    "«Bonjour», dit-il.",
    # Numbers: \p{N}{1,3} groups across scripts.
    "1234567 12 3.14159 2024年",
    "２０２４年１２月",
    "مرحبا بالعالم ١٢٣٤٥",
    "x² + ½ = Ⅻ ①②③④",
    "abc１２３def 007",
    # Japanese (kana marks, ・ is \p{P}, ゛ is \p{S}, ー is \p{L}).
    "カタカナ・ひらがな、漢字ゔ゛ーです。",
    "ｶﾀｶﾅ ﾃｽﾄ",
    # Korean, Thai (combining vowel marks), Greek, Cyrillic, Arabic.
    "안녕하세요, 세계! 123",
    "สวัสดีครับ ภาษาไทย",
    "Γειά σου Κόσμε. Привет, мир!",
    # Combining marks (precomposed vs decomposed; mark after a space).
    "café café ́x ë́",
    # Emoji: \p{S}, variation selector (\p{M}), ZWJ (\p{Cf}).
    "I ❤️ Rust 🦀🦀!",
    "👨‍👩‍👧 family",
    # Non-ASCII whitespace.
    "a b　c  　d e",
    "\t  word next",
    # Controls / format chars (unmatched by the regex: own pieces).
    "a\x00b\x01\x02 c​d﻿e",
    # CJK outside regex 2's range (Ext A/B, U+9FA6+).
    "㐀𠀀鿦 龥一",
    # Math / currency symbols.
    "x ≤ y ≠ z ∑∫ €5 £3 ¥100",
    # Code and ASCII whitespace edge cases.
    "fn main() {\n    let x = 42;\n}\n",
    "It's they're 'quoted' .foo ->bar",
    "a  \n\n  b\t\tc   ",
    "\r\n\r\n  \r\n x",
]


def _gpt2_table():
    tbl, n = [], 0
    for b in range(256):
        if (33 <= b <= 126) or (161 <= b <= 172) or b >= 174:
            tbl.append(chr(b))
        else:
            tbl.append(chr(256 + n))
            n += 1
    return tbl


_BYTE_TO_CP = _gpt2_table()


def byte_encode(s):
    return "".join(_BYTE_TO_CP[b] for b in s.encode("utf-8"))


def main():
    path = sys.argv[1]
    tok = Tokenizer.from_file(path)
    tj = json.load(open(path, encoding="utf-8"))
    vocab = dict(tj["model"]["vocab"])
    for a in tj["added_tokens"]:
        vocab[a["content"]] = a["id"]
    merges = [m if isinstance(m, str) else " ".join(m) for m in tj["model"]["merges"]]

    cases = []
    for text in CASES:
        pieces = [text[a:b] for _, (a, b) in tok.pre_tokenizer.pre_tokenize_str(text)]
        assert "".join(pieces) == text
        ids = tok.encode(text, add_special_tokens=False).ids
        cases.append({"text": text, "pieces": pieces, "ids": ids})

    universe = "\n".join(byte_encode(c["text"]) for c in cases)
    keep = {i: t for t, i in vocab.items() if len(t.encode()) == 1 or t in universe}
    kept_merges = [m for m in merges if m.replace(" ", "", 1) in universe]
    doc = {
        "_comment": (
            "GENERATED by scripts/gen_joyai_pretok_vectors.py from the model's tokenizer.json "
            "with HF tokenizers: reference pieces and ids per case, plus a trimmed vocab "
            "(real ids, merge order kept) sufficient by construction for these texts."
        ),
        "vocab_size": max(vocab.values()) + 1,
        "cases": cases,
        "tokens": {str(i): t for i, t in sorted(keep.items())},
        "merges": kept_merges,
    }
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "crates", "v4flash-core", "tests", "data", "joyai_pretok_goldens.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=0)
        f.write("\n")
    sys.stderr.write(f"{len(cases)} cases; {len(keep)} tokens, {len(kept_merges)} merges kept\n")


if __name__ == "__main__":
    main()
