//! PIL-semantics RGB8 resampling: `Image.resize(size)` (default BICUBIC for
//! RGB) and `ImageOps.pad(image, size, color)` (= `ImageOps.contain` +
//! centred paste), reimplemented from Pillow's `libImaging/Resample.c` and
//! `ImageOps.py`.
//!
//! Faithfulness notes:
//! * Bicubic kernel a = −0.5, support 2, antialiased when downscaling
//!   (filter stretched by `in/out`), coefficients normalised per output
//!   pixel, then converted to 22-bit fixed point (`PRECISION_BITS = 32-8-2`)
//!   with round-half-away and accumulated with a half-ulp bias, exactly as
//!   Pillow's 8-bit path does; horizontal pass first, u8 intermediate, then
//!   vertical.
//! * `contain`/`pad` use Python `round()` (half-to-even) for the fitted edge
//!   and for the centred paste offset. VERIFIED against Pillow 12.3.0's
//!   own source: `ImageOps.contain` computes `new_height =
//!   round(image.height / image.width * size[0])` and `ImageOps.pad`
//!   computes `x = round((size[0] - resized.width) * centering[0])`.
//!   (Much older Pillow truncated with `int()`, which differs by one
//!   pixel whenever the delta is odd; that is NOT the version in play.)
//!
//! VERIFICATION: byte-exact against real Pillow 12.3.0 over 21 resize/pad
//! cases — `tests/pillow_vectors.rs` against
//! `tests/data/pillow_resize_cases.json`, regenerated by
//! `scripts/gen_pillow_resize_vectors.py` under
//! `nix-shell -p 'python3.withPackages(ps: [ps.pillow])'`. Includes
//! letterbox deltas ≡ 3 (mod 4), where `round()` and `int()` disagree.

use color_eyre::eyre::{self, eyre};

/// Interleaved RGB8, row-major, no padding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rgb {
    pub w: u32,
    pub h: u32,
    pub data: Vec<u8>,
}

impl Rgb {
    pub fn new(w: u32, h: u32, data: Vec<u8>) -> Rgb {
        assert_eq!(data.len(), (w as usize) * (h as usize) * 3);
        Rgb { w, h, data }
    }
    pub fn filled(w: u32, h: u32, rgb: [u8; 3]) -> Rgb {
        let mut data = Vec::with_capacity((w as usize) * (h as usize) * 3);
        for _ in 0..(w as usize) * (h as usize) {
            data.extend_from_slice(&rgb);
        }
        Rgb { w, h, data }
    }
    #[inline]
    pub fn px(&self, x: u32, y: u32, c: usize) -> u8 {
        self.data[((y as usize) * (self.w as usize) + x as usize) * 3 + c]
    }
    /// Paste `src` at (x0, y0); must fit.
    pub fn paste(&mut self, src: &Rgb, x0: u32, y0: u32) {
        assert!(x0 + src.w <= self.w && y0 + src.h <= self.h, "paste out of bounds");
        let sw = src.w as usize * 3;
        for y in 0..src.h as usize {
            let d0 = ((y0 as usize + y) * self.w as usize + x0 as usize) * 3;
            self.data[d0..d0 + sw].copy_from_slice(&src.data[y * sw..(y + 1) * sw]);
        }
    }
}

const PRECISION_BITS: u32 = 32 - 8 - 2;
const BICUBIC_SUPPORT: f64 = 2.0;

/// Pillow's `bicubic_filter` (a = −0.5).
#[inline]
fn bicubic_filter(x: f64) -> f64 {
    const A: f64 = -0.5;
    let x = x.abs();
    if x < 1.0 {
        ((A + 2.0) * x - (A + 3.0)) * x * x + 1.0
    } else if x < 2.0 {
        (((x - 5.0) * x + 8.0) * x - 4.0) * A
    } else {
        0.0
    }
}

/// Pillow `precompute_coeffs` + `normalize_coeffs_8bpc` for one axis.
/// Returns per output index `(xmin, fixed-point weights)`.
fn coeffs(in_size: u32, out_size: u32) -> Vec<(usize, Vec<i32>)> {
    let scale = in_size as f64 / out_size as f64;
    let filterscale = scale.max(1.0);
    let support = BICUBIC_SUPPORT * filterscale;
    let ss = 1.0 / filterscale;
    let one = (1i64 << PRECISION_BITS) as f64;
    (0..out_size)
        .map(|xx| {
            let center = (xx as f64 + 0.5) * scale;
            // C `(int)` truncates toward zero; Rust `as i64` too.
            let xmin = ((center - support + 0.5) as i64).max(0) as usize;
            let xmax = ((center + support + 0.5) as i64).min(in_size as i64) as usize;
            let mut k: Vec<f64> = (xmin..xmax)
                .map(|x| bicubic_filter((x as f64 - center + 0.5) * ss))
                .collect();
            let ww: f64 = k.iter().sum();
            if ww != 0.0 {
                for v in k.iter_mut() {
                    *v /= ww;
                }
            }
            let kk = k
                .iter()
                .map(|&v| if v < 0.0 { (-0.5 + v * one) as i32 } else { (0.5 + v * one) as i32 })
                .collect();
            (xmin, kk)
        })
        .collect()
}

#[inline]
fn clip8(acc: i64) -> u8 {
    (acc >> PRECISION_BITS).clamp(0, 255) as u8
}

fn resample_horizontal(src: &Rgb, out_w: u32) -> Rgb {
    let kk = coeffs(src.w, out_w);
    let mut out = vec![0u8; out_w as usize * src.h as usize * 3];
    let sw = src.w as usize;
    let ow = out_w as usize;
    for y in 0..src.h as usize {
        let row = &src.data[y * sw * 3..(y + 1) * sw * 3];
        for (xx, (xmin, k)) in kk.iter().enumerate() {
            for c in 0..3 {
                let mut acc: i64 = 1 << (PRECISION_BITS - 1);
                for (i, &w) in k.iter().enumerate() {
                    acc += row[(xmin + i) * 3 + c] as i64 * w as i64;
                }
                out[(y * ow + xx) * 3 + c] = clip8(acc);
            }
        }
    }
    Rgb { w: out_w, h: src.h, data: out }
}

fn resample_vertical(src: &Rgb, out_h: u32) -> Rgb {
    let kk = coeffs(src.h, out_h);
    let w = src.w as usize;
    let mut out = vec![0u8; w * out_h as usize * 3];
    for (yy, (ymin, k)) in kk.iter().enumerate() {
        for x in 0..w {
            for c in 0..3 {
                let mut acc: i64 = 1 << (PRECISION_BITS - 1);
                for (i, &wgt) in k.iter().enumerate() {
                    acc += src.data[((ymin + i) * w + x) * 3 + c] as i64 * wgt as i64;
                }
                out[(yy * w + x) * 3 + c] = clip8(acc);
            }
        }
    }
    Rgb { w: src.w, h: out_h, data: out }
}

/// `image.resize((out_w, out_h))` with Pillow's default RGB filter (BICUBIC).
pub fn resize_bicubic(src: &Rgb, out_w: u32, out_h: u32) -> eyre::Result<Rgb> {
    if out_w == 0 || out_h == 0 {
        return Err(eyre!("resize: height and width must be > 0 (got {out_w}x{out_h})"));
    }
    if src.w == out_w && src.h == out_h {
        return Ok(src.clone());
    }
    // Borrow through the passes instead of cloning the source up front:
    // a full-size copy of a decoded image is pure waste, and this runs on
    // a request-serving thread.
    let horiz = (src.w != out_w).then(|| resample_horizontal(src, out_w));
    let cur: &Rgb = horiz.as_ref().unwrap_or(src);
    if cur.h != out_h {
        return Ok(resample_vertical(cur, out_h));
    }
    Ok(horiz.unwrap_or_else(|| src.clone()))
}

/// Python `round()`: round half to even.
pub fn py_round(v: f64) -> i64 {
    let r = v.round(); // half away from zero
    if (v - v.trunc()).abs() == 0.5 {
        // exact tie → even
        let t = v.trunc() as i64;
        if t % 2 == 0 {
            t
        } else {
            r as i64
        }
    } else {
        r as i64
    }
}

/// `ImageOps.contain(image, (out_w, out_h))`: fit inside the box keeping
/// aspect; returns the resized image (≤ box on one axis).
pub fn contain(src: &Rgb, out_w: u32, out_h: u32) -> eyre::Result<Rgb> {
    let im_ratio = src.w as f64 / src.h as f64;
    let dest_ratio = out_w as f64 / out_h as f64;
    let (mut w, mut h) = (out_w, out_h);
    if im_ratio != dest_ratio {
        if im_ratio > dest_ratio {
            let new_h = py_round(src.h as f64 / src.w as f64 * out_w as f64);
            if new_h != out_h as i64 {
                h = new_h.max(0) as u32;
            }
        } else {
            let new_w = py_round(src.w as f64 / src.h as f64 * out_h as f64);
            if new_w != out_w as i64 {
                w = new_w.max(0) as u32;
            }
        }
    }
    resize_bicubic(src, w, h)
}

/// `ImageOps.pad(image, (out_w, out_h), color=rgb)` with centering (0.5, 0.5).
pub fn pad_contain(src: &Rgb, out_w: u32, out_h: u32, color: [u8; 3]) -> eyre::Result<Rgb> {
    let resized = contain(src, out_w, out_h)?;
    if resized.w == out_w && resized.h == out_h {
        return Ok(resized);
    }
    let mut out = Rgb::filled(out_w, out_h, color);
    if resized.w != out_w {
        let x = py_round((out_w - resized.w) as f64 * 0.5) as u32;
        out.paste(&resized, x, 0);
    } else {
        let y = py_round((out_h - resized.h) as f64 * 0.5) as u32;
        out.paste(&resized, 0, y);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_is_exact() {
        let mut d = Vec::new();
        for i in 0..(9 * 7 * 3) {
            d.push((i * 37 % 256) as u8);
        }
        let img = Rgb::new(9, 7, d);
        // Same size takes the copy path; force the resampler via 2-step.
        let up = resample_horizontal(&img, 9);
        assert_eq!(up, img);
        let up = resample_vertical(&img, 7);
        assert_eq!(up, img);
    }

    #[test]
    fn solid_stays_solid() {
        let img = Rgb::filled(20, 30, [200, 17, 90]);
        for (w, h) in [(7, 11), (40, 61), (20, 3), (1, 1), (100, 100)] {
            let r = resize_bicubic(&img, w, h).unwrap();
            assert!(r.data.chunks(3).all(|p| p == [200, 17, 90]), "{w}x{h}");
        }
    }

    #[test]
    fn py_round_half_even() {
        assert_eq!(py_round(2.5), 2);
        assert_eq!(py_round(3.5), 4);
        assert_eq!(py_round(1.4999), 1);
        assert_eq!(py_round(0.5), 0);
        assert_eq!(py_round(317.33), 317);
    }

    #[test]
    fn pad_letterboxes_and_centres() {
        // 28x42 source into 322x476 → contain gives 317x476, paste at x=2.
        let img = Rgb::filled(28, 42, [10, 20, 30]);
        let out = pad_contain(&img, 322, 476, [127, 127, 127]).unwrap();
        assert_eq!((out.w, out.h), (322, 476));
        assert_eq!([out.px(0, 0, 0), out.px(1, 5, 1), out.px(319, 9, 2), out.px(321, 475, 0)], [127; 4]);
        assert_eq!([out.px(2, 0, 0), out.px(318, 475, 2)], [10, 30]);
    }
}
